[project]
name = "ht-ibkr-integrations"
version = "0.3.0"
description = "Utilities and tools for algorithmic trading using IBKR TWS API"
authors = [
    { name = "Robert Boivin", email = "your_email@example.com" },
    { name = "Gregory Delespes", email = "gregory.delespes@gmail.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "protobuf (==5.29.3)",
    "schedule>=1.2.0",
    "ibapi @ https://interactivebrokers.github.io/downloads/twsapi_macunix.1037.02.zip#subdirectory=IBJts/source/pythonclient"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
scan = "app.main:main"
loadstrategy = "app.loadstrategy:main"
init-db = "app.utils.db_init:initialize_database"
close-positions = "app.close_open_positions:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.setuptools.package-data]
app = ["config.json", "dto/table_definitions.sql", "strategies/*.json"]